parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection:   default
        connections:
            default:
                driver: 'pdo_pgsql'
                server_version: 10.3
                charset: UTF8
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        default_entity_manager:  redes
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            redes:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine'
                        prefix: 'App\Entity'
                        alias: App
