App\Entity\Redes\Vlan:
    type: entity
    table: redes.vlan
    indexes:
        IDX_A0DF018CBE2FFB85:
            columns:
                - switch_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        descricao:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        servicoId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: servico_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        switches:
            targetEntity: App\Entity\Redes\Switches
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                switch_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
