App\Entity\Redes\Porta:
    type: entity
    table: redes.porta
    indexes:
        IDX_3FA113F5BE2FFB85:
            columns:
                - switch_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        porta:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        adminStatus:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: down(2)
            column: admin_status
        operStatus:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: oper_status
        autoNeg:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: auto_neg
        speed:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        duplex:
            type: string
            nullable: true
            length: 13
            options:
                fixed: false
        modo:
            type: string
            nullable: false
            length: 14
            options:
                fixed: false
        vlanBase:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: vlan_base
        flowCtrl:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
            column: flow_ctrl
    manyToOne:
        switches:
            targetEntity: App\Entity\Redes\Switches
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                switch_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
